In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('placement2.csv')

In [3]:
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [4]:
df.shape

(200, 2)

In [5]:
X = df.iloc[:,0:1]
y = df.iloc[:,1:]

In [6]:
X.head()

cgpa
0  6.89
1  5.12
2  7.82
3  7.42
4  6.94

In [7]:
X.shape

(200, 1)

In [8]:
y.head()

package
0     3.26
1     1.98
2     3.25
3     3.67
4     3.57

In [9]:
y.shape

(200, 1)

### Using sklearn Linear regression model

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [11]:
X_train

cgpa
156  7.38
115  8.35
155  6.98
15   7.25
61   5.48
..    ...
0    6.89
184  7.88
131  6.37
152  7.37
106  6.13

[160 rows x 1 columns]

In [12]:
X_train.shape

(160, 1)

In [13]:
y_train

package
156     3.13
115     4.21
155     3.09
15      3.23
61      1.61
..       ...
0       3.26
184     3.14
131     2.01
152     3.08
106     2.19

[160 rows x 1 columns]

In [14]:
y_train.shape

(160, 1)

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
lr = LinearRegression()

In [17]:
lr.fit(X_train,y_train)

LinearRegression()

In [18]:
y_pred =lr.predict(X_test)

In [19]:
y_pred

array([[4.39751239],
       [4.32680345],
       [3.10707437],
       [3.11885919],
       [2.5355105 ],
       [2.1583962 ],
       [3.16010607],
       [2.44712434],
       [2.28213683],
       [3.55489761],
       [3.07761232],
       [3.84362575],
       [3.16010607],
       [2.51783327],
       [4.00272085],
       [2.84780829],
       [2.77709936],
       [3.24259983],
       [2.93030204],
       [2.94797928],
       [3.42526457],
       [1.7282502 ],
       [4.1382463 ],
       [2.83602347],
       [2.33516853],
       [3.17189089],
       [3.54311279],
       [1.88734529],
       [2.82423864],
       [3.35455564],
       [3.20724536],
       [2.31159889],
       [2.37641541],
       [3.19546054],
       [3.94968915],
       [2.34106094],
       [2.9597641 ],
       [3.45472662],
       [2.70639042],
       [2.31159889]])

In [20]:
from sklearn.metrics import r2_score

In [21]:
r2_score(y_test,y_pred)

0.6516754875100943

In [22]:
lr.coef_

array([[0.5892411]])

In [23]:
lr.intercept_

array([-1.12956915])

### Making Multiple Linear Regression Model 

In [24]:
class LRModel:
    def __int__(self):
        self.coef_ = None
        self.intercept_ = None

    
    def fit(self,X_train,y_train):
        #pass
        #print(X_train.shape)
        X_train = np.insert(X_train,0,1,axis=1)

        #calculate coef_
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]
        #print(betas)
    
    
    def predict(self,X_test):
        #pass
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [25]:
lr = LRModel()

In [26]:
lr.fit(X_train,y_train)

In [27]:
y_pred = lr.predict(X_test)

In [28]:
y_pred

array([[4.39751239],
       [4.32680345],
       [3.10707437],
       [3.11885919],
       [2.5355105 ],
       [2.1583962 ],
       [3.16010607],
       [2.44712434],
       [2.28213683],
       [3.55489761],
       [3.07761232],
       [3.84362575],
       [3.16010607],
       [2.51783327],
       [4.00272085],
       [2.84780829],
       [2.77709936],
       [3.24259983],
       [2.93030204],
       [2.94797928],
       [3.42526457],
       [1.7282502 ],
       [4.1382463 ],
       [2.83602347],
       [2.33516853],
       [3.17189089],
       [3.54311279],
       [1.88734529],
       [2.82423864],
       [3.35455564],
       [3.20724536],
       [2.31159889],
       [2.37641541],
       [3.19546054],
       [3.94968915],
       [2.34106094],
       [2.9597641 ],
       [3.45472662],
       [2.70639042],
       [2.31159889]])

In [29]:
r2_score(y_test,y_pred)

0.6516754875101021

In [30]:
lr.coef_

array([[0.5892411]])

In [31]:
lr.intercept_

array([-1.12956915])